### ISSUE TITLE
Upload dataset in specific schema

### ISSUE THREAD

**Issue by githilman** [MPalix86/programmatically_upload_csv_in_superset#1]
Just wondering can I upload the dataset in specific schema in the target database?
And another problem maybe everytime I upload new data to the dataset the chart using dataset got broke. Any idea how to make it works? Really appreciate it. Thanks

**Comment by MPalix86** [comment]
No but I can actually make it work with a specific schema, if you need let me know. 
My charts also didn't broke but  I guess it could be the metrics, I can't figure it out how to add the default metrics, to fix this just go to metrics custom sql and write your metrics, this can fix the chart, the most common metrics is COUNT(*).
